### ISSUE TITLE
unable to understand Readme file

### ISSUE THREAD

**Issue by vikilleaks** [yangl1996/prism-rust#109]
Inside the section "Experimental Flow" I am unable to understand the 2nd command:
`python3 scripts/generate_topo.py <NUM NODES> randreg <DEGREE> > randreg.json`

Please help me figure out `<NUM NODES> randreg <DEGREE>` in this command.

**Comment by yangl1996** [comment]
randreg means random regular (graph). It should be kept as-is in the command.

**Comment by vikilleaks** [comment]
For my system what values can I specify for <NUM NODES> and <DEGREE> ?
How do we figure out these 2 values?
