### ISSUE TITLE
Step 3 of Experimental Flow 

### ISSUE THREAD

**Issue by vikilleaks** [yangl1996/prism-rust#110]
I'm running an instance using SSH client. I followed all the steps as per Readme.md of testbed however on running `./run.sh build` I received the following error:

```
Copying local repository to build machine
ssh: Could not resolve hostname prism: Temporary failure in name resolution
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.2]
ssh: Could not resolve hostname prism: Temporary failure in name resolution
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.2]
ssh: Could not resolve hostname prism: Temporary failure in name resolution
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.2]
Building Prism binary
Stripping symbol
ssh: Could not resolve hostname prism: Temporary failure in name resolution
Finished

```

Any help will be highly appreciated.

**Comment by yangl1996** [comment]
Did you set up the ssh config directory correctly? It looks like ssh cannot find your AWS instances.

**Comment by yangl1996** [comment]
Also, did you finish all the steps listed _before_ experimental flow in `testbed/README.md`?

**Comment by vikilleaks** [comment]
@yangl1996 I did all the steps inside the section "Set up AWS account". However, there are a couple of changes due to the unavailability of particular names:
1. My EC2 key-pair name is `prism-attempt1`
2. My S3 bucket's name is also `prism-attempt1`
So, my S3 bucket's policy is :
```
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "AddPerm",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::prism-binary/*"
        }
    ]
}
```

Next, I launched an EC2 instance using the launch template. Then, I cloned the prism-rust repo. 
After this, I did steps 1 and 2 of the section "Install Dependencies".
Again, my private key's name is "prism-attempt1.pem" and not "prism.pem"

**Comment by yangl1996** [comment]
Hmmm did you try running `ssh prism`?

**Comment by vikilleaks** [comment]
@yangl1996 I am able to run `ssh -i "prism-attempt1.pem" PUBLIC DNS of my instance` on my local machine to connect to the EC2 instance.
Can you clarify what will happen on running `ssh prism` ?

**Comment by vikilleaks** [comment]
Should we do the steps in Install Dependencies section in our local machine or after launching the EC2 instance.
Also, I don't understand step 7 of Install Dependencies section.

**Comment by vikilleaks** [comment]
@yangl1996  I'm getting this error for `ssh prism` 
`ssh: Could not resolve hostname prism: Name or service not known`

**Comment by yangl1996** [comment]
Yes, you need to go through Install Dependencies. You should be able to log into your build machine when `ssh prism` - the script uses that machine to build the binary. Note that you can simple set ~/.ssh/config so that `ssh prism` logs back into your own machine, provided it’s a Linux.

I think it would really help to read `run.sh` (and other files it use) to understand what it tries to do.

**Comment by yangl1996** [comment]
Also, note that in Setting up AWS, what you create is not an instance, but a Launch Template.

This is the high-level flow of the experiment.


0. The experiment assumes you work on macOS or Linux.
1. Follow carefully _all the steps before_ "Experimental Flow". I think the key pair name must be prism the way the script is written. You may use another name for the key pair, but you'll need to modify run.sh to make it work. Should not be a big change though.
2. When you run ./run.sh build, the script tries to connect to a build machine. It copies the code there, and compiles the code. It then copies back the binary. The build machine could be the same as your current machine (e.g., the laptop where you run ./run.sh), as long as it is Linux and has all rust tool chains installed.
3. The script calls Amazon API to start EC2 instances using the launch template you just set.
4. The script copies the binary and other support file to AWS, and runs the experiment.

Step 7 of installing dependencies is very important. Basically, you install all the tools needed to build the prism binary.

Indeed, the whole setup is a bit complex, and requires basic proficiency of Linux and/or UNIX.

**Comment by vikilleaks** [comment]
1. So, I don't need to run the EC2 instance on my own right? run.sh will take care of that?

2. Also, all the steps inside "Install Dependencies" are to be done in our local system?

3. We need to create a new Ubuntu VM that is accessible using `ssh prism`. This VM will act as a build machine. So, there are 3 requirements: Local machine, build machine and EC2 instance. `ssh prism` has nothing to do with the EC2 instance?

**Comment by yangl1996** [comment]
> * So, I don't need to run the EC2 instance on my own right? run.sh will take care of that?

Correct.

> * Also, all the steps inside "Install Dependencies" are to be done in our local system?

Correct.

> * We need to create a new Ubuntu VM that is accessible using `ssh prism`. This VM will act as a build machine. So, there are 3 requirements: Local machine, build machine and EC2 instance. `ssh prism` has nothing to do with the EC2 instance?

Correct. And as mentioned above, if your local computer is a linux and you can install the toolchain there, you could set `~/.ssh/config` such that `ssh prism` logs back into your local computer.

**Comment by yangl1996** [comment]
Closing because this is a question rather than an issue.

**Comment by vikilleaks** [comment]
> Also, note that in Setting up AWS, what you create is not an instance, but a Launch Template.
> 
> This is the high-level flow of the experiment.
> 
> 1. The experiment assumes you work on macOS or Linux.
> 2. Follow carefully _all the steps before_ "Experimental Flow". I think the key pair name must be prism the way the script is written. You may use another name for the key pair, but you'll need to modify run.sh to make it work. Should not be a big change though.
> 3. When you run ./run.sh build, the script tries to connect to a build machine. It copies the code there, and compiles the code. It then copies back the binary. The build machine could be the same as your current machine (e.g., the laptop where you run ./run.sh), as long as it is Linux and has all rust tool chains installed.
> 4. The script calls Amazon API to start EC2 instances using the launch template you just set.
> 5. The script copies the binary and other support file to AWS, and runs the experiment.
> 
> Step 7 of installing dependencies is very important. Basically, you install all the tools needed to build the prism binary.
> 
> Indeed, the whole setup is a bit complex, and requires basic proficiency of Linux and/or UNIX.

@yangl1996 here the build machine is an ubuntu VM using VirtualBox/VMWare or the EC2 VM we created using the Launch Template in Step 4 of "Set up AWS account"?

**Comment by yangl1996** [comment]
>> We need to create a new Ubuntu VM that is accessible using ssh prism. This VM will act as a build machine. So, there are 3 requirements: Local machine, build machine and EC2 instance. ssh prism has nothing to do with the EC2 instance?

> Correct. And as mentioned above, if your local computer is a linux and you can install the toolchain there, you could set ~/.ssh/config such that ssh prism logs back into your local computer. In other word, "local machine" and "build machine" could be the same one, provided that ssh prism on the local machine logs back into itself.

**Comment by vikilleaks** [comment]
@yangl1996 I used "ssh prism" to log back into my local computer. Now, when I do "./run.sh build" I get the following output:

```
Copying local repository to build machine
Building Prism binary
```

However it runs into an infinite loop I guess. After stopping the process using Ctrl+C, I get the following error:

```
Stripping symbol
cp: cannot stat '/home/vivek/prism/target/release/prism': No such file or directory
Finished
```
Please look into this.

**Comment by yangl1996** [comment]
Again, I think it'd be useful to read and understand `testbed` directory.

**Comment by vikilleaks** [comment]
@yangl1996 can you tell me how much time it takes on average for "./run.sh build" to execute?

**Comment by yangl1996** [comment]
The first run usually takes 10 minutes. It needs to compile RocksDB. Subsequent runs should be much faster.

**Comment by vikilleaks** [comment]
@yangl1996 thanks. I have mentioned the detailed steps that I have followed in this [document](https://docs.google.com/document/d/1aW2EpXDR8B93n8NB7mO_eQ5qZR7e60FVADE7_FCrWG4/edit?usp=sharing). I don't know if you have the time to go through it.

**Comment by vikilleaks** [comment]
> > Start a local Ubuntu 18.04 VM that has Rust toolchain, clang, build-essential installed, is accessible by ssh prism, and can read the Github repository (preferably through SSH agent forwarding), so that it can compile the binary
> 
> Your local machine should satisfy this requirement.

@yangl1996 all 4 requirements are satisfied in my system. I have Rust toolchain, clang, build-essential installed and "ssh prism" logs back to my local machine.
Kindly check the screenshot below.

![Screenshot from 2021-04-08 20-57-53](https://user-images.githubusercontent.com/32481163/114054232-4b98c780-98ad-11eb-8423-ebc156d3d59a.png)

**Comment by vikilleaks** [comment]
@yangl1996 I checked run.sh and the code is stopping on this line:
`ssh prism -- 'cd ~/prism && ~/.cargo/bin/cargo build --release' &> log/prism_build.log`
Can you tell me what this line is doing?

**Comment by yangl1996** [comment]
Then it’s compiling the code. It’s not an infinite loop then. Your local machine is properly set up. Congrats!

Please give it 10-40 minutes depending on the speed of your local machine.

**Comment by vikilleaks** [comment]
@yangl1996 there were a couple of issues:
1. The command at line 159 of run.sh should be `ssh prism -- 'cd ~/prism **&& cargo clean** && ~/.cargo/bin/cargo build --release' &> log/prism_build.log`
cargo clean is important otherwise we'll get the following error:
`[Blocking] waiting for file lock on build directory`
2. There is a file named "prism" inside the cloned repo at prism-rust/target/release/ which is absent inside the code (this directory is named "prism") which is copied as a result from "./run.sh build". This leads to the following error:
`cp: cannot stat '/home/vivek/prism/target/release/prism': No such file or directory`

**Comment by vikilleaks** [comment]
@yangl1996 sorry to bother you again.
I was trying the next command `./run.sh start-instances 100`
I am getting the following error:
`An error occurred (InvalidLaunchTemplateId.NotFound) when calling the RunInstances operation: The specified launch template, with template ID lt-0a87e286967856102, does not exist.`

However, this launch template does exist. Please check the attached image:

![Screenshot from 2021-04-08 22-05-56](https://user-images.githubusercontent.com/32481163/114063803-9e2ab180-98b6-11eb-9ab9-ecb241267794.png)
Please see to this.

**Comment by ritvikagrawal1** [comment]
> `An error occurred (InvalidLaunchTemplateId.NotFound) when calling the RunInstances operation: The specified launch template, with template ID lt-0a87e286967856102, does not exist.`

@yangl1996  Can you please help out on this issue?

**Comment by vikilleaks** [comment]
I think the error is here:

Specify the region: Some resources can't be shared between AWS Regions. If you are specifying a resource that's located in a Region other than the default Region (us-east-1), specify its Region in the request. If the resource cannot be found, you get the following error: Client.InvalidResource.NotFound; for example, Client.InvalidInstanceID.NotFound.

**Comment by ritvikagrawal1** [comment]
@yangl1996  What changes need to be made in the code in order to run it on  32 vcpus which will allow us to run a total of 2 x c5d.4xlarge ?
