### ISSUE TITLE
vcpus change 

### ISSUE THREAD

**Issue by ritvikagrawal1** [yangl1996/prism-rust#111]
@yangl1996 @wgr523  @bagavi  @gfanti  
In continuation to this issue : https://github.com/yangl1996/prism-rust/issues/110

Can you please guide on what changes need to be made in order to run it on 32 vcpus which will allow us to run a total of 2 x c5d.4xlarge ?

**Comment by vikilleaks** [comment]
@ritvikagrawal1 you can use 2 c5d.4xlarge instances instead of 100 and try running the code.

**Comment by ritvikagrawal1** [comment]
thanks, @vikilleaks 
issue resolved !
