### ISSUE TITLE
Step 5, 6 and 7 of Experimental Flow

### ISSUE THREAD

**Issue by vikilleaks** [yangl1996/prism-rust#112]
I am able to build and run the instances now.
However, I'm stuck in step 5 and 6.

**Step 5:** `./run.sh tune-tcp`

I'm getting the following error:
```
Executing tune_tcp
Task 23721 failed
Task 23725 failed
Finished
```
**Step 6:** `./run.sh gen-payload randreg.json`

I'm getting the following error:
```
Deleting existing files
Download binaries
vivek@127.0.0.1's password: 
prism-copy                                                                                                 100% 8060KB 115.9MB/s   00:00    
Generate etcd config files for each EC2 instance
Generate prism config files and keypairs for each node
Traceback (most recent call last):
  File "scripts/gen_prism_payload.py", line 55, in <module>
    result = subprocess.run([prism_bin, "keygen", "--addr"], capture_output=True, text=True)
  File "/usr/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '../target/debug/prism': '../target/debug/prism'
Compressing payload files
Payload written
```
The directory named "debug" does not exist in the cloned repo.

Thanks.

**Comment by yangl1996** [comment]
For step 4: wait for 3 minutes, rerun the command.

For step 5: run cargo build —debug locally

**Comment by vikilleaks** [comment]
I don't understand why we have to wait for 3 minutes in Step 4.
I tried multiple times but still the tasks are failing.

**Comment by yangl1996** [comment]
Some EC2 instances have not started, so any attempt to log into that machine and configure anything will fail.

**Comment by vikilleaks** [comment]
Oh okay. Actually I'm just running 2 instances and their state was "Running". This means they have started right?

**Comment by yangl1996** [comment]
There’s an initialization script on the machine. Until the initialization script finishes, the machine is not ready.

Also, there should be a log directory in `testbed/` that you can examine and see what’s going on.

**Comment by vikilleaks** [comment]
Actually, the command to generate debug folder is simply `cargo build`
No --debug is needed.
Thanks for the help.

**Comment by vikilleaks** [comment]
I checked the log file instance-id_tune_tcp.log to find that the name of my SSH key was not prism.pem.
This removed the error in step-5.
Thanks again.

**Comment by vikilleaks** [comment]
@yangl1996 in step-7 `./run.sh sync-payload`, I got the following error:
```
Uploading payload to S3
Downloading payload on each instance
Executing get_payload
Task 5174 failed
Task 5178 failed
Finished
```
I checked the log files and got the following error:
```
Warning: Permanently added 'xx.xx.xxx.xxx' (ECDSA) to the list of known hosts.
--2021-04-17 18:17:29--  https://prism101.s3.amazonaws.com/payload/i-02xxxxxxxxxxxxxxx.tar.gz
Resolving prism101.s3.amazonaws.com (prism-binary.s3.amazonaws.com)... xx.xxx.xx.xx
Connecting to prism101.s3.amazonaws.com (prism-binary.s3.amazonaws.com)|xx.xxx.xx.xx|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-04-17 18:17:30 ERROR 403: Forbidden.
```
The name of my S3 bucket is prism101 and it has the following permissions:

![Screenshot from 2021-04-18 00-07-11](https://user-images.githubusercontent.com/32481163/115123331-29542780-9fda-11eb-9ee9-2c2d8c0ea982.png)

![Screenshot from 2021-04-18 00-07-17](https://user-images.githubusercontent.com/32481163/115123334-2d804500-9fda-11eb-9caf-cfb5234f7bc4.png)

![Screenshot from 2021-04-18 00-07-24](https://user-images.githubusercontent.com/32481163/115123336-307b3580-9fda-11eb-91bc-9cfa7b501aef.png)

Thanks.

**Comment by vikilleaks** [comment]
The S3 bucket is in ap-south-1 while all other stuff is in us-west-2.
Maybe that is the cause of this 403 error code?

**Comment by ritvikagrawal1** [comment]
@yangl1996  can you comment on how can we resolve this ?

**Comment by yangl1996** [comment]
This seems like an S3 permission issue. Did you try moving the S3 bucket to the same region?

Another thing to try is to try to download from S3 (the same file that run.sh tries to download) on an EC2 machine.

Strange though that I've personally set up the testbed on multiple AWS accounts and placed S3 buckets in different regions from where EC2 machines reside, and did not encounter issues.

**Comment by ghost** [comment]
@yangl1996 I have pasted all the permissions for my S3 bucket in the comment above.
Can you look into them and compare with your S3 buckets to see if there are any abnormalities?

**Comment by ghost** [comment]
@yangl1996 I created a new S3 bucket named "prism102" in the same region as my EC2 instances.
I'm still getting 403 Forbidden error:
```
Warning: Permanently added '100.20.156.233' (ECDSA) to the list of known hosts.
--2021-04-18 06:26:08-- https://prism102.s3.amazonaws.com/payload/i-0bee60a660a527aeb.tar.gz
Resolving prism102.s3.amazonaws.com (prism102.s3.amazonaws.com)... 52.218.133.73
Connecting to prism102.s3.amazonaws.com (prism102.s3.amazonaws.com)|52.218.133.73|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-04-18 06:26:08 ERROR 403: Forbidden.
```

Attached below are the permissions for prism102 bucket:

![Screenshot from 2021-04-18 12-00-13](https://user-images.githubusercontent.com/32481163/115136481-b4b2d480-a03d-11eb-94ca-3f222fdaca64.png)

![Screenshot from 2021-04-18 12-00-19](https://user-images.githubusercontent.com/32481163/115136485-b8def200-a03d-11eb-8aa9-764879f211c3.png)

![Screenshot from 2021-04-18 12-00-26](https://user-images.githubusercontent.com/32481163/115136490-bbd9e280-a03d-11eb-9fb9-7b584802bd53.png)

![Screenshot from 2021-04-18 12-00-33](https://user-images.githubusercontent.com/32481163/115136492-be3c3c80-a03d-11eb-86c8-780cb6b9786a.png)

**Comment by ritvikagrawal1** [comment]
@yangl1996 please help out on this

**Comment by ghost** [comment]
@yangl1996 the issue is resolved.
This error is there because our S3 Bucket doesn’t have permissions for the s3:PutObject action on the bucket.
In the readme file, only permission to s3:GetObject is provided but not to s3:PutObject.

Reference: https://aws.amazon.com/premiumsupport/knowledge-center/s3-403-forbidden-error/

So, I used the following bucket policy:

```
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "AddPerm",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::prism101/*"
        }
    ]
}
```
