### ISSUE TITLE
Confirmation rule

### ISSUE THREAD

**Issue by bagavi** [yangl1996/prism-rust#64]
In the current confirmation rule, there can be situations where no leader at level `l` will be confirmed.

Case 1: If two proposer blocks get equal number of votes = `NUM_OF_CHAINS/2`
Case 2: If there are three proposer blocks and none of them have `>NUM_OF_CHAINS/2` votes.

If this happens the ledger will be stalled. The confirmation rule in the paper is as follows:

1. Each proposer block (at level `l`) `p_i` has an upper and lower bounds on its votes.
2. The lower bound (lb) on votes of `p_i` is equal to the total number of votes cast on `p_i`
3. The upper bound (ub) on votes  of `p_i` is equal to the total number of votes cast on `p_i`+ (Number of chains which have not yet voted on level `l`)
4. We confirm the leader block if `max_lb < second_max_ub`.

**Comment by yangl1996** [comment]
done!
